# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:38:30+00:00



import argparse
import json
import os
from datetime import datetime
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyQuery, BaseSecurity

from models import (
    ApiV1CurrenciesHistoryGetResponse,
    ApiV1CurrenciesHistorySupportedGetResponse,
    ApiV1CurrenciesRateGetResponse,
    ApiV1CurrenciesRateSupportedGetResponse,
    ApiV1CurrenciesSummaryGetResponse,
    ApiV1CurrenciesSummarySupportedGetResponse,
    ApiV1MetalsBenchmarkHistoryGetResponse,
    ApiV1MetalsBenchmarkSummaryGetResponse,
    ApiV1MetalsBenchmarkSupportedGetResponse,
    ApiV1MetalsSpotHistoryGetResponse,
    ApiV1MetalsSpotPerformanceAnnualGetResponse,
    ApiV1MetalsSpotPerformanceGetResponse,
    ApiV1MetalsSpotRatioHistoryGetResponse,
    ApiV1MetalsSpotRatioSummaryGetResponse,
    ApiV1MetalsSpotSummaryGetResponse,
    ApiV1MetalsSpotSupportedGetResponse,
    ApiV1MetalsSupportedCurrencyGetResponse,
    Format,
    Unitofmeasure,
)

app = MCPProxy(
    contact={
        'email': 'support@nfusionsolutions.com',
        'name': 'nFusion Solutions',
        'url': 'https://nfusionsolutions.com/contact-us',
        'x-twitter': 'nfusionsolution',
    },
    description='[nFusion Solutions](https://nfusionsolutions.com) provides [REST APIs](https://nfusionsolutions.com/data-feeds/) that deliver enterprise-grade financial data. Data sets include real-time and historical pricing for Spot prices of precious metals such as Gold, Silver, Platinum, and Palladium, exchange rates for major currency pairs, exchange rates for Crypto Currencies such as BTC, ETH, and LTC. All API access requires authentication. In order to be issued access credentials you must first enter into a service agreement with nFusion Solutions and acquire a commercial license. For information on how to obtain a licence [take a tour of our products](https://nfusionsolutions.com/nfusion-solutions-metals-gold-price-feed-tour/) or email sales@nfusionsolutions.com.',
    license={
        'name': 'Commercial License',
        'url': 'https://nfusionsolutions.com/nfusion-solutions-metals-gold-price-feed-quote/',
    },
    title='nFusion Solutions Market Data API',
    version='1',
    servers=[{'url': 'https://api.nfusionsolutions.biz'}],
)


@app.get(
    '/api/v1/Currencies/history',
    description=""" Historical OHLC data for the specified period and interval size

The combination of the interval parameter and start and end dates can result in results
being truncated to conform to result size limits. See comments on interval parameter for details on valid interval values. """,
    tags=['currency_history_data'],
    security=[
        APIKeyQuery(name="token"),
    ],
)
def currencies__history__g_e_t(
    pairs: str,
    start: datetime = ...,
    end: Optional[datetime] = None,
    interval: Optional[str] = None,
    format: Optional[Format] = None,
):
    """
    Get historical prices for requested currency pairs
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Currencies/history/supported',
    description=""" Only the currency pairs in the direction noted can be used with the history endpoint.
For example: USD/CAD is not the same as CAD/USD """,
    tags=['currency_history_data'],
    security=[
        APIKeyQuery(name="token"),
    ],
)
def currencies__supported_currencies__history__g_e_t(format: Optional[Format] = None):
    """
    Get list of currency pairs supported by the history endpoint
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Currencies/rate',
    description=""" Current Mid Rate """,
    tags=['currency_current_rates'],
    security=[
        APIKeyQuery(name="token"),
    ],
)
def currencies__rate__g_e_t(pairs: str, format: Optional[Format] = None):
    """
    Get latest mid rate for requested currency pairs
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Currencies/rate/supported',
    description=""" Any of the currencies in this list can be paired with any other currency in this list when supplied to the Rate endpoint.
For example: USD/CAD,CAD/USD,USD/EUR,EUR/CAD """,
    tags=['currency_current_rates', 'currency_history_data'],
    security=[
        APIKeyQuery(name="token"),
    ],
)
def currencies__supported_currencies__rate__g_e_t(format: Optional[Format] = None):
    """
    Get list of currencies supported by the rate endpoint
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Currencies/summary',
    description=""" Current and daily summary information combined into a single quote """,
    tags=['currency_current_rates', 'currency_history_data'],
    security=[
        APIKeyQuery(name="token"),
    ],
)
def currencies__summary__g_e_t(pairs: str, format: Optional[Format] = None):
    """
    Get latest Summary for requested currency pairs
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Currencies/summary/supported',
    description=""" Only the currency pairs in the direction noted can be used with the Summary endpoint.
For example: USD/CAD is not the same as CAD/USD """,
    tags=['currency_current_rates', 'currency_history_data'],
    security=[
        APIKeyQuery(name="token"),
    ],
)
def currencies__supported_currencies__summary__g_e_t(format: Optional[Format] = None):
    """
    Get list of currency pairs supported by the Summary endpoint
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Metals/benchmark/history',
    description=""" Historical OHLC data for the specified period and interval size

The combination of the interval parameter and start and end dates can result in results
being truncated to conform to result size limits. See comments on interval parameter for details on valid interval values.

The historicalfx flag is used to determine whether to apply today's fx rates to a historical period, or to apply the historical rates from that same time frame. """,
    tags=['metal_benchmark_data'],
    security=[
        APIKeyQuery(name="token"),
    ],
)
def metals__benchmark_history__g_e_t(
    metals: str,
    start: datetime = ...,
    end: Optional[datetime] = None,
    interval: Optional[str] = None,
    historicalfx: Optional[bool] = None,
    currency: Optional[str] = None,
    unitofmeasure: Optional[Unitofmeasure] = None,
    format: Optional[Format] = None,
):
    """
    Get historical benchmark prices for requested metals
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Metals/benchmark/summary',
    description=""" Benchmark price information """,
    tags=['metal_benchmark_data', 'metal_spot_price_data'],
    security=[
        APIKeyQuery(name="token"),
    ],
)
def metals__benchmark_summary__g_e_t(
    metals: str,
    currency: Optional[str] = None,
    unitofmeasure: Optional[Unitofmeasure] = None,
    format: Optional[Format] = None,
):
    """
    Get latest Benchmark prices for requested metals
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Metals/benchmark/supported',
    tags=['currency_current_rates', 'metal_currency_info'],
    security=[
        APIKeyQuery(name="token"),
    ],
)
def metals__benchmark_supported_metals__g_e_t(format: Optional[Format] = None):
    """
    Get list of symbols supported by the benchmark endpoints
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Metals/spot/history',
    description=""" Historical OHLC data for the specified period and interval size

The combination of the interval parameter and start and end dates can result in results
being truncated to conform to result size limits. See comments on interval parameter for details on valid interval values.

The historicalfx flag is used to determine whether to apply today's fx rates to a historical period, or to apply the historical rates from that same time frame. """,
    tags=['metal_spot_price_data', 'metal_benchmark_data'],
    security=[
        APIKeyQuery(name="token"),
    ],
)
def metals__spot_history__g_e_t(
    metals: str,
    start: datetime = ...,
    end: Optional[datetime] = None,
    interval: Optional[str] = None,
    historicalfx: Optional[bool] = None,
    currency: Optional[str] = None,
    unitofmeasure: Optional[Unitofmeasure] = None,
    format: Optional[Format] = None,
):
    """
    Get historical Spot prices for requested metals
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Metals/spot/performance',
    description=""" Historical Performance information """,
    tags=['metal_benchmark_data', 'metal_spot_price_data'],
    security=[
        APIKeyQuery(name="token"),
    ],
)
def metals__spot_historical_performance__g_e_t(
    metals: str,
    currency: Optional[str] = None,
    unitofmeasure: Optional[Unitofmeasure] = None,
    format: Optional[Format] = None,
):
    """
    Get Historical Performance for requested metals
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Metals/spot/performance/annual',
    description=""" Annual Historical Performance information """,
    tags=['metal_benchmark_data', 'metal_spot_price_data'],
    security=[
        APIKeyQuery(name="token"),
    ],
)
def metals__spot_annual_historical_performance__g_e_t(
    metals: str,
    currency: Optional[str] = None,
    unitofmeasure: Optional[Unitofmeasure] = None,
    format: Optional[Format] = None,
    years: Optional[int] = None,
):
    """
    Get Historical Annual Performance for requested metals
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Metals/spot/ratio/history',
    description=""" Historical data for the specified period and interval size

The combination of the interval parameter and start and end dates can result in results
being truncated to conform to result size limits. See comments on interval parameter for details on valid interval values. """,
    tags=['metal_spot_price_data', 'metal_benchmark_data'],
    security=[
        APIKeyQuery(name="token"),
    ],
)
def metals__spot_ratio_history__g_e_t(
    pairs: str,
    start: datetime = ...,
    end: Optional[datetime] = None,
    interval: Optional[str] = None,
    format: Optional[Format] = None,
):
    """
    Get historical Spot Ratio prices for requested metals
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Metals/spot/ratio/summary',
    description=""" Ratios between prices of two metals """,
    tags=['metal_spot_price_data', 'metal_benchmark_data'],
    security=[
        APIKeyQuery(name="token"),
    ],
)
def metals__spot_ratio_summary__g_e_t(pairs: str, format: Optional[Format] = None):
    """
    Get latest Spot Summary for requested metal ratios
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Metals/spot/summary',
    description=""" Current and daily summary information combined into a single quote """,
    tags=['metal_spot_price_data', 'metal_benchmark_data'],
    security=[
        APIKeyQuery(name="token"),
    ],
)
def metals__spot_summary__g_e_t(
    metals: str,
    currency: Optional[str] = None,
    unitofmeasure: Optional[Unitofmeasure] = None,
    format: Optional[Format] = None,
):
    """
    Get latest Spot Summary for requested metals
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Metals/spot/supported',
    tags=['currency_current_rates', 'metal_currency_info'],
    security=[
        APIKeyQuery(name="token"),
    ],
)
def metals__spot_supported_metals__g_e_t(format: Optional[Format] = None):
    """
    Get list of symbols supported by the spot endpoints
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/api/v1/Metals/supported/currency',
    tags=['metal_currency_info', 'currency_current_rates'],
    security=[
        APIKeyQuery(name="token"),
    ],
)
def metals__supported_currencies__metals__g_e_t(format: Optional[Format] = None):
    """
    Get list of currencies supported by metals endpoints for currency conversion
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
