# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:38:30+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, RootModel


class Interval(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    change: Optional[float] = None
    changePercent: Optional[float] = None
    end: Optional[datetime] = None
    high: Optional[float] = None
    last: Optional[float] = None
    low: Optional[float] = None
    open: Optional[float] = None
    start: Optional[datetime] = None


class IntervalCollection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    baseCurrency: Optional[str] = None
    intervals: Optional[List[Interval]] = None
    name: Optional[str] = None
    symbol: Optional[str] = None


class IntervalCollectionResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: Optional[IntervalCollection] = None
    error: Optional[str] = None
    requestedCurrency: Optional[str] = None
    requestedSymbol: Optional[str] = None
    requestedUnitOfMeasure: Optional[str] = None
    success: Optional[bool] = None


class Rate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    symbol: Optional[str] = None
    timestamp: Optional[datetime] = None
    value: Optional[float] = None


class RateResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: Optional[Rate] = None
    error: Optional[str] = None
    requestedCurrency: Optional[str] = None
    requestedSymbol: Optional[str] = None
    requestedUnitOfMeasure: Optional[str] = None
    success: Optional[bool] = None


class Summary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ask: Optional[float] = None
    baseCurrency: Optional[str] = None
    bid: Optional[float] = None
    fiftyTwoWeekHigh: Optional[float] = None
    fiftyTwoWeekLow: Optional[float] = None
    fiftyTwoWeekPercentChange: Optional[float] = None
    fourWeekPercentChange: Optional[float] = None
    high: Optional[float] = None
    last: Optional[float] = None
    low: Optional[float] = None
    oneDayChange: Optional[float] = None
    oneDayPercentChange: Optional[float] = None
    oneDayValue: Optional[float] = None
    open: Optional[float] = None
    symbol: Optional[str] = None
    timeStamp: Optional[datetime] = None
    twelveWeekPercentChange: Optional[float] = None
    yearToDatePercentChange: Optional[float] = None


class SummaryResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data: Optional[Summary] = None
    error: Optional[str] = None
    requestedCurrency: Optional[str] = None
    requestedSymbol: Optional[str] = None
    requestedUnitOfMeasure: Optional[str] = None
    success: Optional[bool] = None


class Format(Enum):
    json = 'json'
    xml = 'xml'


class ApiV1CurrenciesHistoryGetResponse(RootModel[List[IntervalCollectionResponse]]):
    root: List[IntervalCollectionResponse]


class ApiV1CurrenciesHistorySupportedGetResponse(RootModel[List[str]]):
    root: List[str]


class ApiV1CurrenciesRateGetResponse(RootModel[List[RateResponse]]):
    root: List[RateResponse]


class ApiV1CurrenciesRateSupportedGetResponse(RootModel[List[str]]):
    root: List[str]


class ApiV1CurrenciesSummaryGetResponse(RootModel[List[SummaryResponse]]):
    root: List[SummaryResponse]


class ApiV1CurrenciesSummarySupportedGetResponse(RootModel[List[str]]):
    root: List[str]


class Unitofmeasure(Enum):
    mg = 'mg'
    g = 'g'
    kg = 'kg'
    gr = 'gr'
    oz = 'oz'
    toz = 'toz'
    ct = 'ct'
    dwt = 'dwt'


class ApiV1MetalsBenchmarkHistoryGetResponse(
    RootModel[List[IntervalCollectionResponse]]
):
    root: List[IntervalCollectionResponse]


class ApiV1MetalsBenchmarkSummaryGetResponse(RootModel[List[SummaryResponse]]):
    root: List[SummaryResponse]


class ApiV1MetalsBenchmarkSupportedGetResponse(RootModel[List[str]]):
    root: List[str]


class ApiV1MetalsSpotHistoryGetResponse(RootModel[List[IntervalCollectionResponse]]):
    root: List[IntervalCollectionResponse]


class ApiV1MetalsSpotPerformanceGetResponse(
    RootModel[List[IntervalCollectionResponse]]
):
    root: List[IntervalCollectionResponse]


class ApiV1MetalsSpotPerformanceAnnualGetResponse(
    RootModel[List[IntervalCollectionResponse]]
):
    root: List[IntervalCollectionResponse]


class ApiV1MetalsSpotRatioHistoryGetResponse(
    RootModel[List[IntervalCollectionResponse]]
):
    root: List[IntervalCollectionResponse]


class ApiV1MetalsSpotRatioSummaryGetResponse(RootModel[List[SummaryResponse]]):
    root: List[SummaryResponse]


class ApiV1MetalsSpotSummaryGetResponse(RootModel[List[SummaryResponse]]):
    root: List[SummaryResponse]


class ApiV1MetalsSpotSupportedGetResponse(RootModel[List[str]]):
    root: List[str]


class ApiV1MetalsSupportedCurrencyGetResponse(RootModel[List[str]]):
    root: List[str]
